// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var cancelAnimationFrame, last, requestAnimationFrame, vendor, vendors, _i, _len;

  last = null;

  requestAnimationFrame = null;

  cancelAnimationFrame = null;

  if (typeof window !== "undefined" && window !== null) {
    requestAnimationFrame = window.requestAnimationFrame;
    cancelAnimationFrame = window.cancelAnimationFrame;
    vendors = ['ms', 'moz', 'webkit', 'o'];
    for (_i = 0, _len = vendors.length; _i < _len; _i++) {
      vendor = vendors[_i];
      if (requestAnimationFrame) {
        break;
      }
      requestAnimationFrame = window["" + vendor + "RequestAnimationFrame"];
      cancelAnimationFrame = window["" + vendor + "CancelAnimationFrame"];
    }
  }

  if (requestAnimationFrame == null) {
    requestAnimationFrame = function(callback) {
      var delay, now;
      now = new Date().getTime();
      if (last == null) {
        last = now;
      }
      delay = Math.max(0, 16 - (now - last));
      last = now + delay;
      return setTimeout(function() {
        return callback(last);
      }, delay);
    };
  }

  if (cancelAnimationFrame == null) {
    cancelAnimationFrame = function(id) {
      return clearTimeout(id);
    };
  }

  module.exports = {
    cancelAnimationFrame: cancelAnimationFrame,
    requestAnimationFrame: requestAnimationFrame
  };

}).call(this);
